// This file is generated by scripts/generate-ipc-schema.mjs. Do not edit manually.

import { ipcRenderer } from 'electron';

import type { RocPreloadApi } from '../shared/ipc-registry';
import { ipcChannels } from '../shared/ipc-generated';

export const rocApi: RocPreloadApi = {
  app: {
    getStatus: (...args) => ipcRenderer.invoke(ipcChannels.appGetStatus, ...args),
    openSettings: (...args) => ipcRenderer.invoke(ipcChannels.appOpenSettings, ...args),
    openMainPage: (...args) => ipcRenderer.invoke(ipcChannels.appOpenMainPage, ...args),
    onAppearanceUpdated: (callback) => {
      const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload);
      ipcRenderer.on(ipcChannels.appearanceUpdated, listener);
      return () => ipcRenderer.off(ipcChannels.appearanceUpdated, listener);
    },
    onNavigate: (callback) => {
      const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload);
      ipcRenderer.on(ipcChannels.navigate, listener);
      return () => ipcRenderer.off(ipcChannels.navigate, listener);
    }
  },
  window: {
    getState: (...args) => ipcRenderer.invoke(ipcChannels.windowGetState, ...args),
    getBounds: (...args) => ipcRenderer.invoke(ipcChannels.windowGetBounds, ...args),
    minimize: (...args) => ipcRenderer.invoke(ipcChannels.windowMinimize, ...args),
    toggleMaximize: (...args) => ipcRenderer.invoke(ipcChannels.windowToggleMaximize, ...args),
    close: (...args) => ipcRenderer.invoke(ipcChannels.windowClose, ...args)
  },
  tasks: {
    getSnapshot: (...args) => ipcRenderer.invoke(ipcChannels.tasksGetSnapshot, ...args),
    getThreadMessages: (...args) => ipcRenderer.invoke(ipcChannels.tasksGetThreadMessages, ...args),
    listBackgroundTasks: (...args) => ipcRenderer.invoke(ipcChannels.tasksListBackgroundTasks, ...args),
    deleteThread: (...args) => ipcRenderer.invoke(ipcChannels.tasksDeleteThread, ...args),
    createBackgroundTaskPreview: (...args) => ipcRenderer.invoke(ipcChannels.tasksCreateBackgroundPreview, ...args),
    createBackgroundTask: (...args) => ipcRenderer.invoke(ipcChannels.tasksCreateBackgroundTask, ...args),
    pauseBackgroundTask: (...args) => ipcRenderer.invoke(ipcChannels.tasksPauseBackgroundTask, ...args),
    resumeBackgroundTask: (...args) => ipcRenderer.invoke(ipcChannels.tasksResumeBackgroundTask, ...args),
    cancelBackgroundTask: (...args) => ipcRenderer.invoke(ipcChannels.tasksCancelBackgroundTask, ...args),
    getActiveTasks: (...args) => ipcRenderer.invoke(ipcChannels.tasksGetActiveTasks, ...args),
    getTaskDetail: (...args) => ipcRenderer.invoke(ipcChannels.tasksGetTaskDetail, ...args),
    listScheduledRuns: (...args) => ipcRenderer.invoke(ipcChannels.tasksListScheduledRuns, ...args),
    runBackgroundNow: (...args) => ipcRenderer.invoke(ipcChannels.tasksRunBackgroundNow, ...args),
    deleteBackgroundTask: (...args) => ipcRenderer.invoke(ipcChannels.tasksDeleteBackgroundTask, ...args),
    updateBackgroundTask: (...args) => ipcRenderer.invoke(ipcChannels.tasksUpdateBackgroundTask, ...args),
    getSchedulerStatus: (...args) => ipcRenderer.invoke(ipcChannels.tasksGetSchedulerStatus, ...args),
    onUpdated: (callback) => {
      const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload);
      ipcRenderer.on(ipcChannels.tasksUpdated, listener);
      return () => ipcRenderer.off(ipcChannels.tasksUpdated, listener);
    }
  },
  lifecycle: {
    getTraySummary: (...args) => ipcRenderer.invoke(ipcChannels.lifecycleGetTraySummary, ...args),
    pauseBackgroundExecution: (...args) => ipcRenderer.invoke(ipcChannels.lifecyclePauseBackground, ...args),
    resumeBackgroundExecution: (...args) => ipcRenderer.invoke(ipcChannels.lifecycleResumeBackground, ...args)
  },
  diagnostics: {
    samplePerformance: (...args) => ipcRenderer.invoke(ipcChannels.diagnosticsSamplePerformance, ...args),
    createDiagnosticPackage: (...args) => ipcRenderer.invoke(ipcChannels.diagnosticsCreatePackage, ...args),
    runChecks: (...args) => ipcRenderer.invoke(ipcChannels.diagnosticsRunChecks, ...args),
    getMetricsSnapshot: (...args) => ipcRenderer.invoke(ipcChannels.diagnosticsGetMetricsSnapshot, ...args),
    runHealthCheck: (...args) => ipcRenderer.invoke(ipcChannels.diagnosticsRunHealthCheck, ...args)
  },
  memory: {
    status: (...args) => ipcRenderer.invoke(ipcChannels.memoryStatus, ...args),
    readFile: (...args) => ipcRenderer.invoke(ipcChannels.memoryReadFile, ...args),
    writeFile: (...args) => ipcRenderer.invoke(ipcChannels.memoryWriteFile, ...args),
    snapshotPreview: (...args) => ipcRenderer.invoke(ipcChannels.memorySnapshotPreview, ...args)
  },
  sessions: {
    list: (...args) => ipcRenderer.invoke(ipcChannels.sessionMessagesList, ...args),
    search: (...args) => ipcRenderer.invoke(ipcChannels.sessionMessagesSearch, ...args)
  },
  settings: {
    get: (...args) => ipcRenderer.invoke(ipcChannels.settingsGet, ...args),
    save: (...args) => ipcRenderer.invoke(ipcChannels.settingsSave, ...args),
    testProvider: (...args) => ipcRenderer.invoke(ipcChannels.settingsTestProvider, ...args),
    setProviderSecret: (...args) => ipcRenderer.invoke(ipcChannels.settingsSetProviderSecret, ...args),
    clearProviderSecret: (...args) => ipcRenderer.invoke(ipcChannels.settingsClearProviderSecret, ...args),
    getHooks: (...args) => ipcRenderer.invoke(ipcChannels.settingsHooksGet, ...args),
    saveHooks: (...args) => ipcRenderer.invoke(ipcChannels.settingsHooksSave, ...args),
    trustHook: (...args) => ipcRenderer.invoke(ipcChannels.settingsHooksTrust, ...args)
  },
  mcp: {
    listServers: (...args) => ipcRenderer.invoke(ipcChannels.mcpListServers, ...args),
    ensureExaPreset: (...args) => ipcRenderer.invoke(ipcChannels.mcpEnsureExaPreset, ...args),
    upsertServer: (...args) => ipcRenderer.invoke(ipcChannels.mcpUpsertServer, ...args),
    setServerEnabled: (...args) => ipcRenderer.invoke(ipcChannels.mcpSetServerEnabled, ...args),
    deleteServer: (...args) => ipcRenderer.invoke(ipcChannels.mcpDeleteServer, ...args),
    testServer: (...args) => ipcRenderer.invoke(ipcChannels.mcpTestServer, ...args),
    getConfig: (...args) => ipcRenderer.invoke(ipcChannels.mcpGetConfig, ...args),
    setApprovalMode: (...args) => ipcRenderer.invoke(ipcChannels.mcpSetApprovalMode, ...args)
  },
  skills: {
    list: (...args) => ipcRenderer.invoke(ipcChannels.skillsList, ...args),
    importSkill: (...args) => ipcRenderer.invoke(ipcChannels.skillsImport, ...args),
    setEnabled: (...args) => ipcRenderer.invoke(ipcChannels.skillsSetEnabled, ...args),
    deleteSkill: (...args) => ipcRenderer.invoke(ipcChannels.skillsDelete, ...args),
    listFiles: (...args) => ipcRenderer.invoke(ipcChannels.skillsListFiles, ...args),
    readFile: (...args) => ipcRenderer.invoke(ipcChannels.skillsReadFile, ...args)
  },
  agent: {
    getStatus: (...args) => ipcRenderer.invoke(ipcChannels.agentGetStatus, ...args),
    getConfigPreview: (...args) => ipcRenderer.invoke(ipcChannels.agentGetConfigPreview, ...args),
    getCapabilityPreview: (...args) => ipcRenderer.invoke(ipcChannels.agentGetCapabilityPreview, ...args)
  },
  chat: {
    startRun: (...args) => ipcRenderer.invoke(ipcChannels.chatStartRun, ...args),
    cancelRun: (...args) => ipcRenderer.invoke(ipcChannels.chatCancelRun, ...args),
    resumeRun: (...args) => ipcRenderer.invoke(ipcChannels.chatResumeRun, ...args),
    getRunEvents: (...args) => ipcRenderer.invoke(ipcChannels.chatGetRunEvents, ...args),
    getActiveRun: (...args) => ipcRenderer.invoke(ipcChannels.chatGetActiveRun, ...args),
    onRunEvent: (callback) => {
      const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload);
      ipcRenderer.on(ipcChannels.chatRunEvent, listener);
      return () => ipcRenderer.off(ipcChannels.chatRunEvent, listener);
    }
  },
  workspace: {
    getCurrent: (...args) => ipcRenderer.invoke(ipcChannels.workspaceGetCurrent, ...args),
    select: (...args) => ipcRenderer.invoke(ipcChannels.workspaceSelect, ...args),
    selectFromDialog: (...args) => ipcRenderer.invoke(ipcChannels.workspaceSelectFromDialog, ...args),
    onChanged: (callback) => {
      const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload);
      ipcRenderer.on(ipcChannels.workspaceChanged, listener);
      return () => ipcRenderer.off(ipcChannels.workspaceChanged, listener);
    }
  },
  files: {
    selectFromDialog: (...args) => ipcRenderer.invoke(ipcChannels.filesSelectFromDialog, ...args),
    listTree: (...args) => ipcRenderer.invoke(ipcChannels.filesListTree, ...args),
    search: (...args) => ipcRenderer.invoke(ipcChannels.filesSearch, ...args),
    preview: (...args) => ipcRenderer.invoke(ipcChannels.filesPreview, ...args),
    previewPdf: (...args) => ipcRenderer.invoke(ipcChannels.filesPreviewPdf, ...args),
    writeText: (...args) => ipcRenderer.invoke(ipcChannels.filesWriteText, ...args)
  },
  git: {
    status: (...args) => ipcRenderer.invoke(ipcChannels.gitStatus, ...args),
    diffStat: (...args) => ipcRenderer.invoke(ipcChannels.gitDiffStat, ...args),
    fileDiff: (...args) => ipcRenderer.invoke(ipcChannels.gitFileDiff, ...args),
    stageFile: (...args) => ipcRenderer.invoke(ipcChannels.gitStageFile, ...args),
    stageFiles: (...args) => ipcRenderer.invoke(ipcChannels.gitStageFiles, ...args),
    unstageFile: (...args) => ipcRenderer.invoke(ipcChannels.gitUnstageFile, ...args),
    discardFile: (...args) => ipcRenderer.invoke(ipcChannels.gitDiscardFile, ...args),
    commit: (...args) => ipcRenderer.invoke(ipcChannels.gitCommit, ...args),
    push: (...args) => ipcRenderer.invoke(ipcChannels.gitPush, ...args),
    listBranches: (...args) => ipcRenderer.invoke(ipcChannels.gitListBranches, ...args),
    createBranch: (...args) => ipcRenderer.invoke(ipcChannels.gitCreateBranch, ...args),
    checkoutBranch: (...args) => ipcRenderer.invoke(ipcChannels.gitCheckoutBranch, ...args)
  },
  terminal: {
    createSession: (...args) => ipcRenderer.invoke(ipcChannels.terminalCreateSession, ...args),
    writeInput: (...args) => ipcRenderer.invoke(ipcChannels.terminalWriteInput, ...args),
    resize: (...args) => ipcRenderer.invoke(ipcChannels.terminalResize, ...args),
    closeSession: (...args) => ipcRenderer.invoke(ipcChannels.terminalCloseSession, ...args),
    onOutput: (callback) => {
      const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload);
      ipcRenderer.on(ipcChannels.terminalOutput, listener);
      return () => ipcRenderer.off(ipcChannels.terminalOutput, listener);
    },
    onExit: (callback) => {
      const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload);
      ipcRenderer.on(ipcChannels.terminalExit, listener);
      return () => ipcRenderer.off(ipcChannels.terminalExit, listener);
    }
  },
  rtk: {
    status: (...args) => ipcRenderer.invoke(ipcChannels.rtkStatus, ...args)
  },
  shell: {
    execute: (...args) => ipcRenderer.invoke(ipcChannels.shellExecute, ...args),
    confirm: (...args) => ipcRenderer.invoke(ipcChannels.shellConfirm, ...args)
  }
};
